# Build Stage
FROM node:22-bookworm-slim AS build

WORKDIR /app/frontend

COPY package*.json /app/frontend/

RUN npm install

COPY . /app/frontend/

RUN npm run build


# Production Stage
FROM nginx:alpine3.20-slim

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/frontend/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]