FROM node:22-bookworm-slim

ENV NODE_ENV=development

ENV API_PORT=4000

WORKDIR /app/backend

COPY package*.json /app/backend/

RUN npm install

COPY . /app/backend/

CMD ["npm", "run", "dev"]
